# Generated by Django 4.2.6 on 2023-11-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('telephone', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
